### ISSUE TITLE
Compiling image_classifier/apps/desktop/benchmark.cc failed

### ISSUE THREAD

**Issue by IDwangluting** [SunAriesCN/image-classifier#2]
use command  ./bazel_run_benchmark.sh Compile file,

➜  image-classifier git:(master) ✗ ./bazel_run_benchmark.sh
DEBUG: /private/var/tmp/_bazel_luting/b6d3287d3c019b788a0f7e1db37ec775/external/rules_foreign_cc/workspace_definitions.bzl:15:10: WARNING: This branch is deprecated and no longer recieving updates. Please update to `main` or choose a specific commit to pin in your workspace.
INFO: Build options --compilation_mode, --cpu, --crosstool_top, and 1 more have changed, discarding analysis cache.
INFO: Analyzed target //image_classifier/apps/desktop:image_classifier_benchmark (0 packages loaded, 1724 targets configured).
INFO: Found 1 target...
ERROR: /Users/luting/Desktop/image-classifier/image_classifier/apps/desktop/BUILD:43:11: Compiling image_classifier/apps/desktop/benchmark.cc failed: (Exit 1): wrapped_clang failed: error executing command external/local_config_cc/wrapped_clang '-D_FORTIFY_SOURCE=1' -fstack-protector -fcolor-diagnostics -Wall -Wthread-safety -Wself-assign -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG ... (remaining 101 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox wrapped_clang failed: error executing command external/local_config_cc/wrapped_clang '-D_FORTIFY_SOURCE=1' -fstack-protector -fcolor-diagnostics -Wall -Wthread-safety -Wself-assign -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG ... (remaining 101 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
image_classifier/apps/desktop/benchmark.cc:15:10: fatal error: 'opencv2/opencv.hpp' file not found
#include <opencv2/opencv.hpp>
         ^~~~~~~~~~~~~~~~~~~~
1 error generated.
Target //image_classifier/apps/desktop:image_classifier_benchmark failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 2.200s, Critical Path: 1.53s
INFO: 5 processes: 5 internal.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully

**Comment by SunAriesCN** [comment]
Hi, it's seem that you had no OpenCV on your platform. You can check the comment of `third_party/opencv_*.BUILD` and install opencv by following the comment in `opencv_*.BUILD`. Thanks for your reply, I will try to improve my `README.md` quickly.

**Comment by SunAriesCN** [comment]
@IDwangluting Hi, any problem update about it?
